# Generated by Django 5.2 on 2025-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLightConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_duration', models.PositiveIntegerField(default=30, verbose_name='Red Duration (seconds)')),
                ('yellow_duration', models.PositiveIntegerField(default=5, verbose_name='Yellow Duration (seconds)')),
                ('green_duration', models.PositiveIntegerField(default=25, verbose_name='Green Duration (seconds)')),
                ('current_state', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], default='Red', max_length=10, verbose_name='Current State')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
